ARG version=8
FROM almalinux:${version}
ARG version
ENV VERSION=${version}
ARG COURSE="Docker" \
    TRAINER="Satish" \
    DURATION="10HRS" \
    AUTHOR="Satish"
RUN echo "Trainer is:${TRAINER},version is:${VERSION}"
CMD ["sleep","100"]