ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    TRAINER="Satish" \
    DURATION="10HRS" \
    AUTHOR="Satish"
RUN echo "Trainer is:${TRAINER},version is:${version}"
CMD ["sleep","100"]